[Improvement] - Readme and Tests
betrybe/sd-0x-mysql-vocabulary-booster pull request #15
Opened 2021-03-11 11:12 UTC by LizzardMedeiros

- [x] Ajustes no Readme
- [x] Ajustes nos describes
- [x] Ajustes no main.yml
- [x] Criação da Rubrica 
- [x] Ajustes no testes 

[Rubrica](https://github.com/betrybe/sd-0x-mysql-vocabulary-booster-rubric/pull/1)
[Testes](https://github.com/betrybe/sd-0x-mysql-vocabulary-booster-tests/pull/4)

2021-03-11 12:21 UTC, brunobatista25 requested changes

2021-03-11 12:21 UTC, brunobatista25 commented on README.md
> +Link: [FORMULÁRIO DE AVALIAÇÃO DE PROJETO](https://bit.ly/2OfLJPn)
altera esse cara, volta ele pro link antigo

2021-03-17 21:17 UTC, roziscoding approved these changes

2021-03-18 02:17 UTC, GabrielCoruja approved these changes

2021-03-18 20:05 UTC, merged